# Generated by Django 4.2.2 on 2023-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
