# Generated by Django 4.2.2 on 2023-06-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_course_contents_delete_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='card_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='course',
            name='card_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='card_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
