# Generated by Django 4.2.2 on 2023-06-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_course_card_image_course_card_text_course_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
