# Generated by Django 4.2.2 on 2023-06-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_feedback_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
